"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import jsPDF from "jspdf";

import {
  Sparkles,
  Copy,
  Download,
  Check,
  CheckCircle2,
  LoaderCircle,
  FileText,
  Clock,
  Brain,
  BookOpen,
} from "lucide-react";

type SummaryCardProps = {
  summary: string;
  loading: boolean;

  onGenerateQuiz: () => void;
  quizLoading: boolean;

  onGenerateFlashcards: () => void;
  flashcardLoading: boolean;
};

export default function SummaryCard({
  summary,
  loading,
  onGenerateQuiz,
  quizLoading,
  onGenerateFlashcards,
  flashcardLoading,
}: SummaryCardProps) {
  const [copied, setCopied] = useState(false);

  async function copySummary() {
    if (!summary) return;

    await navigator.clipboard.writeText(summary);

    setCopied(true);

    setTimeout(() => setCopied(false), 2000);
  }

  function downloadPDF() {
    if (!summary) return;

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("✦ NOVA AI Summary", 20, 20);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    const lines = doc.splitTextToSize(summary, 170);

    doc.text(lines, 20, 35);

    doc.save("NOVA_AI_Summary.pdf");
  }

  const wordCount = summary
    ? summary.split(/\s+/).filter(Boolean).length
    : 0;

return (
  <div
    className="
      bg-white
      rounded-3xl
      border
      border-slate-200
      shadow-sm
      p-6
      flex
      flex-col
      h-full
    "
  >
    {/* Header */}

    <div className="flex items-center justify-between mb-6">

      <div className="flex items-center gap-3">

        <div className="w-12 h-12 rounded-2xl bg-sky-100 flex items-center justify-center">

          <Brain
            className="text-sky-600"
            size={22}
          />

        </div>

        <div>

          <h2 className="text-xl font-bold text-slate-900">
            AI Summary
          </h2>

          <p className="text-sm text-slate-500">
            Generated by NOVA AI
          </p>

        </div>

      </div>

      {summary && (

        <div className="flex flex-wrap gap-2">

          {/* Copy */}

          <button
            onClick={copySummary}
            className="
              flex
              items-center
              gap-2
              px-4
              py-2.5
              rounded-xl
              border
              border-slate-200
              bg-white
              hover:bg-slate-50
              transition-all
              duration-300
            "
          >

            {copied ? (

              <>
                <Check
                  size={18}
                  className="text-emerald-600"
                />

                <span className="text-slate-700">
                  Copied
                </span>

              </>

            ) : (

              <>
                <Copy
                  size={18}
                  className="text-slate-600"
                />

                <span className="text-slate-700">
                  Copy
                </span>

              </>

            )}

          </button>

          {/* Download */}

          <button
            onClick={downloadPDF}
            className="
              flex
              items-center
              gap-2
              px-4
              py-2.5
              rounded-xl
              border
              border-slate-200
              bg-white
              hover:bg-slate-50
              transition-all
              duration-300
            "
          >

            <Download
              size={18}
              className="text-slate-600"
            />

            <span className="text-slate-700">
              PDF
            </span>

          </button>

          {/* Flashcards */}

          <button
            onClick={onGenerateFlashcards}
            disabled={flashcardLoading || !summary}
            className="
              flex
              items-center
              gap-2
              px-4
              py-2.5
              rounded-xl
              bg-emerald-100
              text-emerald-700
              hover:bg-emerald-200
              transition-all
              duration-300
              disabled:opacity-50
            "
          >

            <BookOpen size={18} />

            {flashcardLoading
              ? "Generating..."
              : "Flashcards"}

          </button>

          {/* Quiz */}

          <button
            onClick={onGenerateQuiz}
            disabled={quizLoading || !summary}
            className="
              flex
              items-center
              gap-2
              px-4
              py-2.5
              rounded-xl
              bg-sky-500
              hover:bg-sky-600
              text-white
              shadow-sm
              transition-all
              duration-300
              disabled:opacity-50
            "
          >

            <Sparkles size={18} />

            {quizLoading
              ? "Generating..."
              : "Generate Quiz"}

          </button>

        </div>

      )}

    </div>

           {/* Loading */}

      {loading ? (

        <div className="flex-1 flex flex-col justify-center items-center">

          <div className="w-20 h-20 rounded-full bg-sky-100 flex items-center justify-center">

            <LoaderCircle
              className="animate-spin text-sky-600"
              size={40}
            />

          </div>

          <h2 className="text-2xl font-bold mt-8 text-slate-900">
            NOVA AI is Thinking...
          </h2>

          <p className="text-slate-500 mt-3">
            Creating structured exam-ready notes...
          </p>

        </div>

      ) : !summary ? (

        <div className="flex-1 flex flex-col justify-center items-center text-center">

          <div className="w-24 h-24 rounded-full bg-sky-100 flex items-center justify-center">

            <Sparkles
              size={48}
              className="text-sky-600"
            />

          </div>

          <h2 className="text-3xl font-bold mt-8 text-slate-900">
            AI Summary
          </h2>

          <p className="mt-4 text-slate-500 max-w-sm leading-7">
            Upload your notes or a PDF and NOVA AI will generate
            structured revision notes in seconds.
          </p>

        </div>

      ) : (

        <>

          {/* Stats */}

          <div className="grid grid-cols-2 gap-4 mb-5">

            <div className="rounded-2xl bg-slate-50 border border-slate-200 p-4">

              <div className="flex items-center gap-2 text-sm text-slate-500">

                <FileText size={16} />

                Words

              </div>

              <h3 className="text-2xl font-bold mt-2 text-slate-900">
                {wordCount}
              </h3>

            </div>

            <div className="rounded-2xl bg-slate-50 border border-slate-200 p-4">

              <div className="flex items-center gap-2 text-sm text-slate-500">

                <Clock size={16} />

                Generated

              </div>

              <h3 className="text-lg font-semibold mt-2 text-slate-900">
                Just Now
              </h3>

            </div>

          </div>

          {/* Summary */}

          <div
            className="
              flex-1
              overflow-y-auto
              rounded-2xl
              border
              border-slate-200
              bg-slate-50
              p-6

              text-slate-700
              leading-8

              [&_h1]:text-3xl
              [&_h1]:font-bold
              [&_h1]:text-slate-900

              [&_h2]:text-2xl
              [&_h2]:font-bold
              [&_h2]:text-sky-700
              [&_h2]:mt-8

              [&_h3]:text-xl
              [&_h3]:font-semibold
              [&_h3]:text-slate-900
              [&_h3]:mt-6

              [&_ul]:list-disc
              [&_ul]:pl-6
              [&_ul]:space-y-3

              [&_ol]:list-decimal
              [&_ol]:pl-6
              [&_ol]:space-y-3

              [&_li]:leading-7

              [&_strong]:text-slate-900

              [&_blockquote]:border-l-4
              [&_blockquote]:border-sky-300
              [&_blockquote]:pl-4
              [&_blockquote]:italic

              [&_code]:bg-slate-200
              [&_code]:px-1.5
              [&_code]:py-1
              [&_code]:rounded
            "
          >

            <ReactMarkdown>
              {summary}
            </ReactMarkdown>

          </div>

          {/* Footer */}

          <div className="mt-5 flex items-center justify-between text-sm">

            <div className="flex items-center gap-2 text-emerald-600">

              <CheckCircle2 size={18} />

              <span>
                Summary generated successfully
              </span>

            </div>

            <div className="font-medium text-sky-600">

              ✦ NOVA AI

            </div>

          </div>

        </>

      )}

    </div>

  );

}