"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import jsPDF from "jspdf";

import {
  Sparkles,
  Copy,
  Download,
  Check,
  CheckCircle2,
  LoaderCircle,
  FileText,
  Clock,
  Brain,
  BookOpen,
} from "lucide-react";

type SummaryCardProps = {
  summary: string;
  loading: boolean;

  onGenerateQuiz: () => void;
  quizLoading: boolean;

  onGenerateFlashcards: () => void;
  flashcardLoading: boolean;
};

export default function SummaryCard({
  summary,
  loading,

  onGenerateQuiz,
  quizLoading,

  onGenerateFlashcards,
  flashcardLoading,
}: SummaryCardProps) {
  const [copied, setCopied] = useState(false);

  async function copySummary() {
    if (!summary) return;

    await navigator.clipboard.writeText(summary);

    setCopied(true);

    setTimeout(() => setCopied(false), 2000);
  }

  function downloadPDF() {
    if (!summary) return;

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("NOVA AI Summary", 20, 20);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    const lines = doc.splitTextToSize(summary, 170);

    doc.text(lines, 20, 35);

    doc.save("NOVA_AI_Summary.pdf");
  }

  const wordCount = summary
    ? summary.split(/\s+/).filter(Boolean).length
    : 0;

  return (
    <div className="bg-white rounded-3xl shadow-lg border border-stone-200 p-6 flex flex-col h-full">

      {/* Header */}

      <div className="flex items-center justify-between mb-6">

        <div className="flex items-center gap-3">

          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-violet-600 to-indigo-600 flex items-center justify-center">

            <Brain
              className="text-white"
              size={22}
            />

          </div>

          <div>

            <h2 className="text-xl font-bold">
              AI Summary
            </h2>

            <p className="text-sm text-stone-500">
              Generated by NOVA AI
            </p>

          </div>

        </div>

        {summary && (

          <div className="flex flex-wrap gap-2">

            {/* Copy */}

            <button
              onClick={copySummary}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-stone-100 hover:bg-violet-100 transition"
            >

              {copied ? (

                <>
                  <Check
                    size={18}
                    className="text-green-600"
                  />
                  Copied
                </>

              ) : (

                <>
                  <Copy size={18} />
                  Copy
                </>

              )}

            </button>

            {/* PDF */}

            <button
              onClick={downloadPDF}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-stone-100 hover:bg-violet-100 transition"
            >

              <Download size={18} />

              PDF

            </button>

            {/* Flashcards */}

            <button
              onClick={onGenerateFlashcards}
              disabled={flashcardLoading || !summary}
              className="
                flex
                items-center
                gap-2
                px-4
                py-2
                rounded-xl
                bg-green-600
                hover:bg-green-700
                text-white
                transition
                disabled:opacity-50
              "
            >

              <BookOpen size={18} />

              {flashcardLoading
                ? "Generating..."
                : "Flashcards"}

            </button>

            {/* Quiz */}

            <button
              onClick={onGenerateQuiz}
              disabled={quizLoading || !summary}
              className="
                flex
                items-center
                gap-2
                px-4
                py-2
                rounded-xl
                bg-violet-600
                hover:bg-violet-700
                text-white
                transition
                disabled:opacity-50
              "
            >

              <Sparkles size={18} />

              {quizLoading
                ? "Generating..."
                : "Generate Quiz"}

            </button>

          </div>

        )}

      </div>

      {/* Loading */}

      {loading ? (

        <div className="flex-1 flex flex-col justify-center items-center">

          <LoaderCircle
            className="animate-spin text-violet-600"
            size={55}
          />

          <h2 className="text-2xl font-bold mt-8">
            NOVA AI is Thinking...
          </h2>

          <p className="text-stone-500 mt-3">
            Creating exam-ready notes...
          </p>

        </div>

      ) : !summary ? (

        <div className="flex-1 flex flex-col justify-center items-center text-center">

          <div className="w-24 h-24 rounded-full bg-violet-100 flex items-center justify-center">

            <Sparkles
              size={50}
              className="text-violet-600"
            />

          </div>

          <h2 className="text-3xl font-bold mt-8">
            AI Summary
          </h2>

          <p className="mt-4 text-stone-500 max-w-sm leading-7">
            Upload a PDF or paste your notes to generate smart revision notes.
          </p>

        </div>

      ) : (

        <>

          <div className="grid grid-cols-2 gap-4 mb-5">

            <div className="rounded-xl bg-stone-100 p-4">

              <div className="flex items-center gap-2 text-sm text-stone-600">

                <FileText size={16} />

                Words

              </div>

              <h3 className="text-2xl font-bold mt-2">

                {wordCount}

              </h3>

            </div>

            <div className="rounded-xl bg-stone-100 p-4">

              <div className="flex items-center gap-2 text-sm text-stone-600">

                <Clock size={16} />

                Generated

              </div>

              <h3 className="text-lg font-semibold mt-2">
                Just Now
              </h3>

            </div>

          </div>

          <div
            className="
              flex-1
              overflow-y-auto
              rounded-2xl
              bg-stone-50
              border
              border-stone-200
              p-6
              text-stone-700
              leading-8

              [&_h1]:text-3xl
              [&_h1]:font-bold
              [&_h1]:text-violet-700

              [&_h2]:text-xl
              [&_h2]:font-bold
              [&_h2]:text-indigo-700

              [&_ul]:list-disc
              [&_ul]:pl-6
              [&_ul]:space-y-3
            "
          >

            <ReactMarkdown>

              {summary}

            </ReactMarkdown>

          </div>

          <div className="mt-5 flex justify-between text-sm text-stone-500">

            <div className="flex items-center gap-2">

              <CheckCircle2
                className="text-green-600"
                size={18}
              />

              Generated Successfully

            </div>

            <span>
              Powered by NOVA AI
            </span>

          </div>

        </>

      )}

    </div>
  );
}